"""Check locale coverage/placeholders and regenerate the explicit UI-template resource index.

Usage: python tools/localization.py [--generate]
English is the Android fallback; values-zh is the source-template catalog.
Only explicit tr(...) calls are translated. User content must never pass through tr as a key.
"""
from pathlib import Path
import argparse
import json
import re
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
RES = ROOT / "app/src/main/res"
KOTLIN = ROOT / "app/src/main/java/dev/qinglan/browser"
INDEX = KOTLIN / "TextResources.kt"


def unescape(value):
    return re.sub(r"\\(u[0-9a-fA-F]{4}|.)", lambda m:
                  chr(int(m[1][1:], 16)) if m[1].startswith("u") else
                  {"n": "\n", "r": "\r", "t": "\t", "b": "\b", '"': '"',
                   "'": "'", "\\": "\\", "$": "$"}.get(m[1], m[0]), value)


def read(directory):
    result = {}
    for node in ET.parse(RES / directory / "strings.xml").getroot():
        key = node.attrib["name"]
        assert key not in result, (directory, "duplicate", key)
        value = node.text or ""
        assert value.startswith('"') and value.endswith('"'), (directory, key, "quote resource text")
        result[key] = unescape(value[1:-1])
    return result


def index_text(source):
    lines = ["package dev.qinglan.browser", "",
             "/** Generated by tools/localization.py from the Simplified Chinese resources. */",
             "internal object TextResources {", "    val ids:Map<String,Int> = mapOf("]
    seen = set()
    for key, value in source.items():
        if value in seen:
            continue
        seen.add(value)
        quoted = json.dumps(value, ensure_ascii=False).replace("$", "\\$")
        lines.append(f"        {quoted} to R.string.{key},")
    return "\n".join(lines + ["    )", "}", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true")
    args = parser.parse_args()
    source = read("values-zh")
    placeholder = re.compile(r"%\d+\$s")
    for language in ("values", "values-b+zh+Hant"):
        translated = read(language)
        assert translated.keys() == source.keys(), (language, "resource coverage differs")
        for key, value in translated.items():
            assert value.strip(), (language, key, "empty translation")
            assert sorted(placeholder.findall(value)) == sorted(placeholder.findall(source[key])), (language, key, "placeholder mismatch")
            if language == "values":
                assert not re.search(r"[\u3400-\u9fff]", value), (key, "untranslated English resource")
    keys = set(source.values())
    # A source literal can contain escaped quotes and dollar signs, but never runtime interpolation.
    pattern = re.compile(r'\btr\("((?:\\.|[^"\\])*)"')
    for file in KOTLIN.glob("*.kt"):
        for match in pattern.finditer(file.read_text(encoding="utf-8")):
            assert unescape(match[1]) in keys, (file.name, "missing resource", match[1])
    expected = index_text(source)
    if args.generate:
        INDEX.write_text(expected, encoding="utf-8")
    else:
        assert INDEX.read_text(encoding="utf-8") == expected, "Run with --generate to update TextResources.kt"
    print(f"PASS: {len(source)} resources in English, Simplified Chinese and Traditional Chinese; placeholders and source keys match.")


if __name__ == "__main__":
    main()
