package dev.qinglan.browser
import org.junit.Assert.*
import org.junit.Test
import org.json.JSONObject

class BackupCryptoTest {
    @Test fun encryptsPasswordsAndRandomizesEveryExport(){val raw=BackupCodec.export(null,null,null,listOf(SavedPassword("https://example.test/","synthetic-user","synthetic-password")));val pass="测试1234".toCharArray();val one=BackupCrypto.encrypt(raw,pass);val two=BackupCrypto.encrypt(raw,pass);assertNotEquals(one,two);assertFalse(one.contains("synthetic-user"));assertFalse(one.contains("synthetic-password"));assertEquals(raw,BackupCrypto.decrypt(one,pass));assertEquals("synthetic-user",BackupCodec.parse(BackupCrypto.decrypt(one,pass)).passwords!!.single().username)}
    @Test fun rejectsWrongPasswordTamperingAndParameters(){val encrypted=BackupCrypto.encrypt("test","1234".toCharArray());assertThrows(IllegalArgumentException::class.java){BackupCrypto.decrypt(encrypted,"wrong".toCharArray())};val o=JSONObject(encrypted);val body=o.getString("ciphertext");o.put("ciphertext",(if(body[0]=='A')"B"else"A")+body.drop(1));assertThrows(IllegalArgumentException::class.java){BackupCrypto.decrypt(o.toString(),"1234".toCharArray())};o.put("iterations",Int.MAX_VALUE);assertThrows(IllegalArgumentException::class.java){BackupCrypto.decrypt(o.toString(),"1234".toCharArray())}}
    @Test fun enforcesMinimumPasswordAndHttpsScope(){assertThrows(IllegalArgumentException::class.java){BackupCrypto.encrypt("test","123".toCharArray())};assertEquals("https://example.test",PasswordCodec.origin("https://EXAMPLE.test:443/path"));assertNotEquals(PasswordCodec.origin("https://example.test"),PasswordCodec.origin("https://example.test:8443"));assertEquals("",PasswordCodec.origin("http://example.test/"));assertEquals("",PasswordCodec.origin("https://user:secret@example.test/"))}
    @Test fun preservesBookmarkFoldersAndOldBackups(){val folder=Visit("Folder","",id="folder",folder=true);val site=Visit("Example","https://example.test/",id="site",parent="folder");val restored=BackupCodec.parse(BackupCodec.export(null,listOf(folder,site),mapOf("palette" to "blue","menuColumns" to 5)));assertTrue(restored.bookmarks!![0].folder);assertEquals("folder",restored.bookmarks[1].parent);assertEquals(5,restored.settings!!["menuColumns"]);assertEquals(1,BackupCodec.parse("""{"format":"qinglan-backup","version":1,"bookmarks":[{"title":"old","url":"https://example.test/"}]}""").bookmarks!!.size)}
    @Test fun historyBoundaries(){val now=System.currentTimeMillis();assertEquals(now-3600000,HistoryRange.start(1,now));assertEquals(now-604800000,HistoryRange.start(3,now));val today=HistoryRange.start(2,now);assertTrue(today<=now&&now-today<25*3600000);assertEquals(Long.MIN_VALUE,HistoryRange.start(0,now))}
}
