package dev.qinglan.browser

import org.junit.Assert.*
import org.junit.Test

class ScriptCodecTest {
    private fun script(extra:String="",match:String="*://*.example.com/*")=UserScript(source="// ==UserScript==\n// @name Test\n// @match $match\n$extra\n// ==/UserScript==\ndocument.title='ok';")
    @Test fun matchesExactHostsSubdomainsAndHttpOnly(){val s=script();assertTrue(s.accepts("https://example.com/x"));assertTrue(s.accepts("http://a.example.com/x"));assertFalse(s.accepts("https://evil-example.com/x"));assertFalse(s.accepts("https://example.com.evil.test/x"));assertFalse(s.accepts("file://example.com/x"))}
    @Test fun excludesAndEscapesRegexCharacters(){val s=script("// @exclude *://*/private*", "https://example.com/a.b?x=*");assertTrue(s.accepts("https://example.com/a.b?x=1#hash"));assertFalse(s.accepts("https://example.com/axb?x=1"));val e=script("// @exclude-match https://example.com/private/*");assertFalse(e.accepts("https://example.com/private/a"));assertTrue(e.accepts("https://example.com/public/a"))}
    @Test fun includeAndExcludedGlob(){val s=UserScript(source="// ==UserScript==\n// @name Glob\n// @include https://*.example.org/*\n// @exclude *://*/private/*\n// ==/UserScript==\n");assertTrue(s.accepts("https://www.example.org/a"));assertFalse(s.accepts("https://www.example.org/private/a"))}
    @Test fun rejectsUnimplementedPrivilegesAndUnsafeDependencies(){listOf("// @grant GM_cookie","// @grant GM_download","// @require http://x.test/lib.js","// @resource css file:///a.css","// @run-at context-menu").forEach{assertThrows(IllegalArgumentException::class.java){script(it)}}}
    @Test fun supportsCommonApisDependenciesAndBodyTiming(){val s=script("// @grant GM_xmlhttpRequest\n// @grant GM.setValue\n// @require https://x.test/lib.js\n// @resource css https://x.test/a.css\n// @connect api.example.org\n// @run-at document-body");assertTrue(s.grants("GM_setValue"));assertTrue(s.grants("GM.xmlhttpRequest"));assertEquals("document-body",s.runAt)}
    @Test fun permitsCopyrightCommentsBeforeMetadata(){val base=script().source;assertEquals("Test",UserScript(source="/* License banner */\n// Copyright\n"+base).name);assertThrows(IllegalArgumentException::class.java){UserScript(source="<html>\n"+base)}}
    @Test fun supportsIdnSuffixWildcardsAndPorts(){val idn=script(match="https://超星.com/*");assertTrue(idn.accepts("https://"+java.net.IDN.toASCII("超星.com")+"/a"));val video=script(match="https://video.sina.*/*");assertTrue(video.accepts("https://video.sina.com.cn/a"));assertFalse(video.accepts("https://evil-video.sina.com/a"));assertTrue(script(match="http://localhost/*").accepts("http://localhost:8895/a"));assertTrue(script(match="https://lemonlive*/*").accepts("https://lemonlive.test/a"))}
    @Test fun defaultMatchesAndRegexIncludes(){val raw="// ==UserScript==\n// @name Default\n// ==/UserScript==\n";assertTrue(UserScript(source=raw).accepts("https://example.org/a"));val regex=script("// @include /^https://other\\.test/(a|b)/\n// @exclude /private/", "https://example.com/*");assertTrue(regex.accepts("https://other.test/a/1"));assertFalse(regex.accepts("https://other.test/a/private"))}
    @Test fun cachedAssetsAndInstallOriginRoundTrip(){val original=script().copy(dependencies=mapOf("https://lib.test/a.js" to "var x=1;"),resources=mapOf("css" to "body{}"),resourceUrls=mapOf("css" to "data:text/css;base64,YQ=="),installUrl="https://greasyfork.org/scripts/1/code/a.user.js");assertEquals(original,ScriptCodec.decode(original.json()));assertFalse(ScriptCodec.javascript(original).contains("window.top!==window||"))}
    @Test fun rejectsMissingOrDangerousPatterns(){assertThrows(IllegalArgumentException::class.java){script(match="file:///*")};assertThrows(IllegalArgumentException::class.java){script(match="https://*evil.test/*")};assertThrows(IllegalArgumentException::class.java){UserScript(source="alert(1)")}}
    @Test fun preservesSourceAndSupportedMetadata(){val s=script("// @grant GM_addStyle\n// @run-at document-start");assertEquals("document-start",s.runAt);assertTrue(ScriptCodec.javascript(s).contains("DOMContentLoaded").not());assertTrue(ScriptCodec.javascript(s).contains(s.source));assertFalse(s.enabled)}
}
